spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_analytics
    username: sparkuser
    password: sparkpass
    driver-class-name: org.postgresql.Driver

spark:
  master: local[*]
  data:
    path: ./data
